blank_issues_enabled: false
contact_links:
  - name: ğŸ“– íŒ€ ë…¸ì…˜ í˜ì´ì§€
    url: https://www.notion.so/Dooring-262c43cb4dc480569d12de12c8bcd526?source=copy_link
    about: í”„ë¡œì íŠ¸ ë¬¸ì„œëŠ” ì—¬ê¸°ì—ì„œ í™•ì¸í•˜ì„¸ìš”
  - name: ğŸ’¬ Discord ì±„ë„
    url: https://discord.gg/xTpXD9xZwY
    about: ë¹ ë¥¸ ì§ˆë¬¸ì€ Discordì—ì„œ í•´ì£¼ì„¸ìš”
